<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-VolleyballClub_Web-bdec6c59-8d14-4a8d-8d4d-9554d08fc294</UserSecretsId>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.12" />
    <PackageReference Include="MudBlazor" Version="9.11.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VolleyballClub.Application\VolleyballClub.Application.csproj" />
    <ProjectReference Include="..\VolleyballClub.Infrastructure\VolleyballClub.Infrastructure.csproj" />
  </ItemGroup>

</Project>
